version: '3'
services:
  web:
    container_name: react
    build:
      context: ./react-tutorial
    volumes:
     - ./react-tutorial:/react-tutorial
    command: sh -c "cd app; yarn start;"
    ports:
     - "3000:3000"
    tty: true